# Generated by Django 4.1 on 2026-01-11 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('inara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='extPosId',
        ),
        migrations.RemoveField(
            model_name='category',
            name='extPosParentId',
        ),
        migrations.RemoveField(
            model_name='category',
            name='posType',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='extPosId',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='extPosParentId',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='posType',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='extPosId',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='orderPKPos',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='extPosId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='extPosId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderPKPos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='extPosId',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='base_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='product_category',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('UNISEX', 'Unisex')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalorderdescription',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalorderdescription',
            name='selected_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='base_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('UNISEX', 'Unisex')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderdescription',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderdescription',
            name='selected_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], max_length=10)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('variant_price', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'DELETED')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inara.item')),
            ],
            options={
                'db_table': 'product_variant',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductVariant',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('color', models.CharField(max_length=50)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], max_length=10)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('variant_price', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'DELETED')], default=1)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inara.item')),
            ],
            options={
                'verbose_name': 'historical product variant',
                'verbose_name_plural': 'historical product variants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalorderdescription',
            name='variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inara.productvariant'),
        ),
        migrations.AddField(
            model_name='orderdescription',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inara.productvariant'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['item', 'status'], name='product_var_item_id_4bba37_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='product_var_sku_3f6862_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('item', 'color', 'size')},
        ),
    ]
